### ISSUE TITLE
copy instead of transferring

### ISSUE THREAD

**Issue by v18281** [Kagu-chan/anki.transfer-review-history#1]
is it possible to copy the review history instead of transferring? i am trying to break one note into multiple notes while retaining the review history so fsrs would work. thank you.

**Comment by Kagu-chan** [comment]
Yep, this probaply makes sense. I'll look into it soon :)

**Comment by v18281** [comment]
thank you.

**Comment by Kagu-chan** [comment]
Theoretically the changes are done and could be used.
However, while Anki sync's those changes properly, the UI doesn't understand that there are changes in the first places, thus not showing the user.
This could lead to lost data or at least confusion if people don't have other sync data available.

Ill try to get this working, then I'll finnish the update.

**Comment by v18281** [comment]
Awesome. You made my day.
